# Generated by Django 3.0 on 2020-01-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='facultysignup',
            fields=[
                ('factid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('dob', models.DateField(max_length=10)),
                ('gender', models.CharField(max_length=30)),
                ('qualification', models.CharField(max_length=30)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=10)),
                ('assbatch', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='sleave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('fromdate', models.DateField(max_length=10)),
                ('todate', models.DateField(max_length=10)),
                ('reason', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('admno', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('dob', models.DateField(max_length=10)),
                ('gender', models.CharField(max_length=30)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('admdate', models.DateField(max_length=10)),
                ('guardian', models.CharField(max_length=30)),
                ('batch', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='studentattantance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=10)),
                ('stdid', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=30)),
                ('hours1status', models.CharField(max_length=15)),
                ('hours2status', models.CharField(max_length=15)),
                ('hours3status', models.CharField(max_length=15)),
                ('hours4status', models.CharField(max_length=15)),
            ],
        ),
    ]
