# Generated by Django 3.0 on 2020-01-09 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_studentmark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentattantance',
            old_name='stdid',
            new_name='sid',
        ),
    ]
